# Generated by Django 4.2.2 on 2023-06-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostsmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default='True'),
        ),
        migrations.AlterField(
            model_name='userpostsmodel',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='user-posts/'),
        ),
    ]
